In [1]:
import pandas as pd
import numpy as np
import warnings
import seaborn as sns 
import re
from ast import literal_eval
warnings.filterwarnings('ignore')
print('pandas:'+pd.__version__)
print('seaborn:'+sns.__version__)  
from sklearn.model_selection import train_test_split 
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer 
import nltk
from sklearn.linear_model import LogisticRegression
nltk.download('stopwords')
from nltk.corpus import stopwords 
from sklearn.multiclass import OneVsRestClassifier
from sklearn import model_selection
from sklearn.model_selection import GridSearchCV
from datetime import datetime
import sqlite3
from sqlite3 import Error
import uuid
from time import time
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

pandas:1.0.5
seaborn:0.10.1

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USUARIO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
results = []
resultsLogisticRegression = []


# datetime object containing current date and time
now = datetime.now()
 
print("now =", now)

# dd/mm/YY H:M:S
dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
print("date and time =", dt_string)

id_transacao = dt_string#str(uuid.uuid4())
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
    except Error as e:
        print(e)

    return conn

def save_metrics(conn, project):
    """
    Create a new project into the projects table
    :param conn:
    :param project:
    :return: project id
    """
    sql = ''' INSERT INTO metrics( classificador, score_f1,
    precision,
    train_time,
    test_time,
    transacao)
    VALUES(?,?,?,?,?,?) '''
    cur = conn.cursor()
    cur.execute(sql, project)
    conn.commit()
    return cur.lastrowid

def salvar_dado(valor):
    database = r"../data/metricsDB.sqlite"
    print (id)
    # create a database connection
    conn = create_connection(database)
    with conn:
        # create a new project
#         linha = ['SGD Classifier',  0.4503092535879421,  1.9019618034362793,  0.012923479080200195, id]
#         metrica = ('Cool App with SQLite & Python', '2015-01-01', '2015-01-30');
        valor.append(id_transacao)
        print(valor)
        metrica = save_metrics( conn,valor) 
    print (id)

now = 2020-10-02 11:29:38.432496
date and time = 02/10/2020 11:29:38

In [3]:
tmdb = pd.read_csv('../../../dados/tmdb_5000_movies.csv')

In [4]:
tmdb['genres'] = tmdb['genres'].fillna('[]')\
.apply(literal_eval).apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])
tmdb.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [5]:
tmdb['genres']=tmdb['genres'].apply(lambda x: '|'.join(x))
tmdb.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,Action|Adventure|Fantasy|Science Fiction,http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,Adventure|Fantasy|Action,http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,Action|Adventure|Crime,http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [6]:
generos = tmdb.genres.str.get_dummies()
generos.head()

,Action,Adventure,Animation,Comedy,Crime,Documentary,Drama,Family,Fantasy,Foreign,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
4,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [7]:
tmdb.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [8]:
tmdb['overview'].fillna('', inplace=True)
tmdb.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   0
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [9]:

# dados_dos_filmes.drop(['budget','homepage','id','keywords','original_language',
#                             'original_title','popularity','production_companies','production_countries',
#                            'release_date','revenue','runtime','spoken_languages','status','tagline',
#                            'title','vote_average','vote_count', 'overview','genres' ], axis=1)

In [10]:
generos = tmdb.genres.str.get_dummies()
generos.head()

#CONCATENA OS DOIS DATAFRAMES
dados_dos_filmes = pd.concat([tmdb, generos], axis=1)
dados_dos_filmes.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,237000000,Action|Adventure|Fantasy|Science Fiction,http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,0,0,0,0,0,1,0,0,0,0
1,300000000,Adventure|Fantasy|Action,http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,0,0,0,0,0,0,0,0,0,0
2,245000000,Action|Adventure|Crime,http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,0,0,0,0,0,0,0,0,0,0
3,250000000,Action|Crime|Drama|Thriller,http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,0,0,0,0,0,0,0,1,0,0
4,260000000,Action|Adventure|Science Fiction,http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,0,0,0,0,0,1,0,0,0,0

In [11]:
# df_genres =dados_dos_filmes.drop(['budget','homepage','id','keywords','original_language',
#                             'original_title','popularity','production_companies','production_countries',
#                            'release_date','revenue','runtime','spoken_languages','status','tagline',
#                            'title','vote_average','vote_count', 'overview','genres' ], axis=1)
# df_genres

In [12]:
df_genres =dados_dos_filmes.drop(['budget','homepage','id','keywords','original_language',
                            'original_title','popularity','production_companies','production_countries',
                           'release_date','revenue','runtime','spoken_languages','status','tagline',
                           'title','vote_average','vote_count', 'overview','genres' ], axis=1)
counts = []
categories = list(df_genres.columns)
for i in categories:
    counts.append((i, df_genres[i].sum()))
df_stats = pd.DataFrame(counts, columns=['genre', '#movies'])
df_stats

              genre  #movies
0            Action     1154
1         Adventure      790
2         Animation      234
3            Comedy     1722
4             Crime      696
5       Documentary      110
6             Drama     2297
7            Family      513
8           Fantasy      424
9           Foreign       34
10          History      197
11           Horror      519
12            Music      185
13          Mystery      348
14          Romance      894
15  Science Fiction      535
16         TV Movie        8
17         Thriller     1274
18              War      144
19          Western       82

In [13]:
# dados_dos_filmes.drop(['budget','homepage','id','keywords','original_language',
#                             'original_title','popularity','production_companies','production_countries',
# #                            'release_date','revenue','runtime','spoken_languages','status','tagline',
#                            'title','vote_average','vote_count', 'overview','genres' ], axis=1)

In [14]:

# split the data, leave 1/3 out for testing
data_x = dados_dos_filmes[['overview']]
data_y = dados_dos_filmes.drop(['budget','homepage','id','keywords','original_language',
                            'original_title','popularity','production_companies','production_countries',
                           'release_date','revenue','runtime','spoken_languages','status','tagline',
                           'title','vote_average','vote_count', 'overview','genres' ], axis=1)
# stratified_split = StratifiedShuffleSplit(n_splits=2, test_size=0.33)
xtrain, xval, ytrain, yval = model_selection.train_test_split(data_x, data_y, test_size=0.33, random_state=512)
# transform matrix of plots into lists to pass to a TfidfVectorizer
train_x = [x[0].strip() for x in xtrain.values.tolist()]
test_x = [x[0].strip() for x in xval.values.tolist()]

In [17]:
from sklearn.naive_bayes import MultinomialNB 
nltk.download('stopwords') 
words = stopwords.words("english") 
pipeline = Pipeline([
('tfidf', TfidfVectorizer(stop_words=words)),
('clf', OneVsRestClassifier(MultinomialNB( fit_prior=True, class_prior=None))),
    
])
parameters = { 
    'tfidf__ngram_range': [(1, 1), (1, 2), (1, 3)],
    'tfidf__max_features': [100, 1000,5000,10000,15000],
    "clf__estimator__alpha": [1e-2, 1e-3,1e-4, 1e-5],
    
}

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USUARIO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [18]:

grid_search_tune = GridSearchCV(
pipeline, parameters, cv=2,  verbose=4) #n_jobs=2,
grid_search_tune.fit(train_x, ytrain )  
print
print("Best parameters set:")
print (grid_search_tune.best_estimator_.steps)

Fitting 2 folds for each of 60 candidates, totalling 120 fits
[CV] clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 1)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV]  clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 1), score=0.063, total=   0.3s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 1)

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s

[CV]  clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 1), score=0.057, total=   0.3s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 2)

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.4s remaining:    0.0s

[CV]  clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 2), score=0.064, total=   0.4s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 2)

[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.8s remaining:    0.0s

[CV]  clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 2), score=0.057, total=   0.5s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 3)

[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    1.3s remaining:    0.0s

[CV]  clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 3), score=0.058, total=   0.7s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 3)

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    2.0s remaining:    0.0s

[CV]  clf__estimator__alpha=0.01, tfidf__max_features=100, tfidf__ngram_range=(1, 3), score=0.056, total=   0.6s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 1), score=0.086, total=   0.3s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 1), score=0.085, total=   0.3s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 2), score=0.089, total=   0.4s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 2), score=0.085, total=   0.4s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 3), score=0.086, total=   0.5s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=1000, tfidf__ngram_range=(1, 3), score=0.084, total=   0.5s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 1), score=0.103, total=   0.2s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 1), score=0.089, total=   0.3s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 2), score=0.098, total=   0.4s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 2), score=0.093, total=   0.5s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 3), score=0.100, total=   0.6s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=5000, tfidf__ngram_range=(1, 3), score=0.094, total=   0.6s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 1), score=0.098, total=   0.3s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 1), score=0.086, total=   0.3s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 2), score=0.103, total=   0.4s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 2), score=0.096, total=   0.5s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 3), score=0.104, total=   0.6s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=10000, tfidf__ngram_range=(1, 3), score=0.096, total=   0.6s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 1), score=0.099, total=   0.3s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 1), score=0.092, total=   0.3s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 2), score=0.104, total=   0.6s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 2), score=0.098, total=   0.5s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 3), score=0.101, total=   0.7s
[CV] clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.01, tfidf__max_features=15000, tfidf__ngram_range=(1, 3), score=0.090, total=   0.6s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 1), score=0.063, total=   0.2s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 1), score=0.057, total=   0.3s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 2), score=0.064, total=   0.4s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 2), score=0.057, total=   0.4s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 3), score=0.058, total=   0.5s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=100, tfidf__ngram_range=(1, 3), score=0.056, total=   0.6s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 1), score=0.085, total=   0.3s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 1), score=0.085, total=   0.3s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 2), score=0.087, total=   0.4s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 2), score=0.085, total=   0.4s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 3), score=0.085, total=   0.6s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=1000, tfidf__ngram_range=(1, 3), score=0.083, total=   0.6s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 1), score=0.091, total=   0.3s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 1), score=0.076, total=   0.3s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 2), score=0.087, total=   0.4s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 2), score=0.082, total=   0.4s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 3)

[CV]  clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 3), score=0.088, total=   0.6s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=5000, tfidf__ngram_range=(1, 3), score=0.080, total=   0.7s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 1), score=0.087, total=   0.3s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 1), score=0.074, total=   0.4s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 2), score=0.094, total=   0.5s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 2), score=0.085, total=   0.5s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 3), score=0.092, total=   0.7s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=10000, tfidf__ngram_range=(1, 3), score=0.085, total=   0.6s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 1), score=0.089, total=   0.3s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 1), score=0.073, total=   0.3s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 2), score=0.094, total=   0.5s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 2), score=0.085, total=   0.6s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 3), score=0.090, total=   0.8s
[CV] clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.001, tfidf__max_features=15000, tfidf__ngram_range=(1, 3), score=0.086, total=   0.8s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 1), score=0.063, total=   0.2s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 1), score=0.057, total=   0.2s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 2), score=0.064, total=   0.4s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 2), score=0.057, total=   0.4s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 3), score=0.058, total=   0.5s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=100, tfidf__ngram_range=(1, 3), score=0.056, total=   0.6s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 1), score=0.084, total=   0.3s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 1), score=0.085, total=   0.2s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 2), score=0.086, total=   0.4s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 2), score=0.084, total=   0.4s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 3), score=0.085, total=   0.6s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=1000, tfidf__ngram_range=(1, 3), score=0.083, total=   0.6s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 1), score=0.089, total=   0.3s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 1), score=0.075, total=   0.3s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 2), score=0.086, total=   0.5s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 2), score=0.080, total=   0.4s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 3), score=0.088, total=   0.6s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=5000, tfidf__ngram_range=(1, 3), score=0.078, total=   0.6s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 1), score=0.083, total=   0.3s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 1), score=0.071, total=   0.3s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 2), score=0.087, total=   0.5s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 2), score=0.079, total=   0.5s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 3), score=0.085, total=   0.6s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=10000, tfidf__ngram_range=(1, 3), score=0.080, total=   0.7s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 1), score=0.088, total=   0.3s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 1), score=0.068, total=   0.3s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 2), score=0.085, total=   0.5s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 2)

[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 2), score=0.080, total=   0.4s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 3), score=0.084, total=   0.6s
[CV] clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=0.0001, tfidf__max_features=15000, tfidf__ngram_range=(1, 3), score=0.080, total=   0.6s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 1), score=0.063, total=   0.3s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 1), score=0.057, total=   0.3s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 2), score=0.064, total=   0.4s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 2), score=0.057, total=   0.4s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 3), score=0.058, total=   0.6s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=100, tfidf__ngram_range=(1, 3), score=0.056, total=   0.6s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 1), score=0.083, total=   0.2s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 1), score=0.085, total=   0.3s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 2), score=0.086, total=   0.4s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 2), score=0.083, total=   0.4s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 3), score=0.085, total=   0.6s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=1000, tfidf__ngram_range=(1, 3), score=0.082, total=   0.6s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 1), score=0.086, total=   0.3s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 1), score=0.073, total=   0.3s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 2), score=0.084, total=   0.4s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 2), score=0.078, total=   0.5s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 3), score=0.086, total=   0.6s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=5000, tfidf__ngram_range=(1, 3), score=0.077, total=   0.6s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 1), score=0.081, total=   0.3s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 1), score=0.070, total=   0.3s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 2), score=0.085, total=   0.4s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 2), score=0.077, total=   0.4s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 3), score=0.084, total=   0.7s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=10000, tfidf__ngram_range=(1, 3), score=0.077, total=   0.7s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 1), score=0.086, total=   0.3s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 1)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 1), score=0.067, total=   0.3s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 2), score=0.085, total=   0.5s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 2)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 2), score=0.078, total=   0.4s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 3), score=0.083, total=   0.6s
[CV] clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 3)
[CV]  clf__estimator__alpha=1e-05, tfidf__max_features=15000, tfidf__ngram_range=(1, 3), score=0.079, total=   0.6s

[Parallel(n_jobs=1)]: Done 120 out of 120 | elapsed:   54.4s finished

Best parameters set:
[('tfidf', TfidfVectorizer(max_features=15000, ngram_range=(1, 2),
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...])), ('clf', OneVsRestClassifier(estimator=MultinomialNB(alpha=0.01)))]

now = 2020-09-30 11:03:43.310300
date and time = 30/09/2020 11:03:43

In [19]:

clf  = grid_search_tune.best_estimator_
classes=categories
print('_' * 120)
print("Training: ")
print(clf)
t0 = time()  
train_time = time() - t0
print("Treino: %0.3fs" % train_time)

t0 = time()
pred = clf.predict(test_x)
test_time = time() - t0
print("testes:  %0.3fs" % test_time)

score = f1_score(yval, pred, average="micro")
precision = precision_score(yval, pred, average='micro')
print("accuracy:   %0.3f" % score)

print('\nAccuracy: {:.2f}\n'.format(accuracy_score(yval, pred)))

print('Micro Precision: {:.2f}'.format(precision_score(yval, pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(yval, pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(yval, pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(yval, pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(yval, pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(yval, pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(yval, pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(yval, pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(yval, pred, average='weighted')))

print("RelatÃ³rio de ClassificaÃ§Ã£o:")
print(classification_report(yval, pred,
#                                             labels=[1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
                                        target_names=classes))

# print("confusion matrix:") 
# print(confusion_matrix(yvalb2.argmax(axis=1), pred.argmax(axis=1)))

 

clf_descr = 'NaiveBayes-semtratamento-tmdb'#str(clf).split('(')[0]

test_time=55555    
results.append([clf_descr, score,precision, train_time, test_time])  
resultsLogisticRegression.append([clf_descr, score,precision, train_time, test_time])  
salvar_dado([clf_descr, score,precision, train_time, test_time])

________________________________________________________________________________________________________________________
Training:
Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=15000, ngram_range=(1, 2),
                                 stop_words=['i', 'me', 'my', 'myself', 'we',
                                             'our', 'ours', 'ourselves', 'you',
                                             "you're", "you've", "you'll",
                                             "you'd", 'your', 'yours',
                                             'yourself', 'yourselves', 'he',
                                             'him', 'his', 'himself', 'she',
                                             "she's", 'her', 'hers', 'herself',
                                             'it', "it's", 'its', 'itself', ...])),
                ('clf',
                 OneVsRestClassifier(estimator=MultinomialNB(alpha=0.01)))])
Treino: 0.000s
testes:  0.199s
accuracy:   0.457

Accuracy: 0.13

Micro Precision: 0.69
Micro Recall: 0.34
Micro F1-score: 0.46

Macro Precision: 0.58
Macro Recall: 0.18
Macro F1-score: 0.24

Weighted Precision: 0.68
Weighted Recall: 0.34
Weighted F1-score: 0.42
RelatÃ³rio de ClassificaÃ§Ã£o:
                 precision    recall  f1-score   support

         Action       0.71      0.41      0.52       377
      Adventure       0.65      0.24      0.35       246
      Animation       1.00      0.08      0.14        66
         Comedy       0.67      0.53      0.59       541
          Crime       0.73      0.19      0.30       241
    Documentary       0.33      0.02      0.04        43
          Drama       0.68      0.65      0.66       768
         Family       0.72      0.13      0.22       136
        Fantasy       0.67      0.17      0.27       128
        Foreign       0.00      0.00      0.00        13
        History       0.25      0.01      0.03        68
         Horror       0.88      0.16      0.27       183
          Music       0.75      0.06      0.10        54
        Mystery       0.71      0.04      0.07       132
        Romance       0.59      0.17      0.27       296
Science Fiction       0.81      0.27      0.40       180
       TV Movie       0.00      0.00      0.00         3
       Thriller       0.71      0.30      0.43       443
            War       0.80      0.09      0.16        44
        Western       0.00      0.00      0.00        25

      micro avg       0.69      0.34      0.46      3987
      macro avg       0.58      0.18      0.24      3987
   weighted avg       0.68      0.34      0.42      3987
    samples avg       0.57      0.38      0.42      3987

<built-in function id>
['LogisticRegression-semtratamento-tmdb', 0.45700903312144525, 0.6860873932697137, 0.0, 55555, '02/10/2020 11:29:38']
<built-in function id>

# Fazendo nova prediÃ§Ã£o com upsample

In [20]:
 tmdb = pd.read_csv('../../../dados/tmdb_5000_movies.csv')

In [21]:
tmdb['genres'] = tmdb['genres'].fillna('[]')\
.apply(literal_eval).apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])
tmdb.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [22]:
tmdb['overview'].fillna('', inplace=True)
tmdb.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   0
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [23]:
overview_df = tmdb[["overview","genres"]]
filmes_balanceados = overview_df.copy(deep=True)

In [24]:
lst_col = 'genres'

filmes_balanceados2 = pd.DataFrame({
      col:np.repeat(filmes_balanceados[col].values, filmes_balanceados[lst_col].str.len())
      for col in filmes_balanceados.columns.drop(lst_col)}
    ).assign(**{
    lst_col:np.concatenate(filmes_balanceados[lst_col].values)})[filmes_balanceados.columns]

In [25]:
filmes_balanceados2['genres'].value_counts()

Drama              2297
Comedy             1722
Thriller           1274
Action             1154
Romance             894
Adventure           790
Crime               696
Science Fiction     535
Horror              519
Family              513
Fantasy             424
Mystery             348
Animation           234
History             197
Music               185
War                 144
Documentary         110
Western              82
Foreign              34
TV Movie              8
Name: genres, dtype: int64

In [26]:
df_Drama = filmes_balanceados2[filmes_balanceados2['genres']=='Drama']
df_Comedy  = filmes_balanceados2[filmes_balanceados2['genres']=='Comedy']
df_Thriller   = filmes_balanceados2[filmes_balanceados2['genres']=='Thriller']
df_Action  = filmes_balanceados2[filmes_balanceados2['genres']=='Action']
df_Romance   = filmes_balanceados2[filmes_balanceados2['genres']=='Romance']
df_Adventure = filmes_balanceados2[filmes_balanceados2['genres']=='Adventure']
df_Crime    = filmes_balanceados2[filmes_balanceados2['genres']=='Crime']
df_Science_Fiction = filmes_balanceados2[filmes_balanceados2['genres']=='Science Fiction']
df_Horror     = filmes_balanceados2[filmes_balanceados2['genres']=='Horror']
df_Family           = filmes_balanceados2[filmes_balanceados2['genres']=='Family']
df_Fantasy    = filmes_balanceados2[filmes_balanceados2['genres']=='Fantasy']
df_Mystery      = filmes_balanceados2[filmes_balanceados2['genres']=='Mystery']
df_Animation   = filmes_balanceados2[filmes_balanceados2['genres']=='Animation']
df_History       = filmes_balanceados2[filmes_balanceados2['genres']=='History']
df_Music         = filmes_balanceados2[filmes_balanceados2['genres']=='Music']
df_War        = filmes_balanceados2[filmes_balanceados2['genres']=='War']
df_Documentary  = filmes_balanceados2[filmes_balanceados2['genres']=='Documentary']
df_Western     = filmes_balanceados2[filmes_balanceados2['genres']=='Western']
df_Foreign     = filmes_balanceados2[filmes_balanceados2['genres']=='Foreign']
df_TV_Movie  = filmes_balanceados2[filmes_balanceados2['genres']=='TV Movie']

In [27]:
from sklearn.utils import resample
df_Comedy  = resample(df_Comedy,
                      replace=True,
                      n_samples=2297,
                      random_state=123)
df_Thriller   = resample(df_Thriller,
                         replace=True,
                         n_samples=2297,
                         random_state=123)
df_Action  = resample(df_Action,
                      replace=True,
                      n_samples=2297,
                      random_state=123)
df_Romance   = resample(df_Romance,
                        replace=True,
                        n_samples=2297,
                        random_state=123)
df_Adventure= resample(df_Adventure, 
                       replace=True,  
                       n_samples=2297,    
                       random_state=123)
df_Crime   = resample(df_Crime,
                      replace=True,     
                      n_samples=2297,    
                      random_state=123)
df_Science_Fiction = resample(df_Science_Fiction,
                              replace=True, 
                              n_samples=2297,
                              random_state=123)
df_Horror     = resample(df_Horror, 
                         replace=True,     
                         n_samples=2297,    
                         random_state=123)
df_Family          = resample(df_Family, 
                              replace=True,
                              n_samples=2297,  
                              random_state=123)
df_Fantasy   = resample(df_Fantasy, 
                                 replace=True,     
                                 n_samples=2297,    
                                 random_state=123)
df_Mystery      = resample(df_Mystery,
                           replace=True,     
                           n_samples=2297,   
                           random_state=123)
df_Animation  = resample(df_Animation, 
                         replace=True, 
                         n_samples=2297, 
                         random_state=123)
df_History    = resample(df_History, 
                         replace=True, 
                         n_samples=2297,  
                         random_state=123)
df_Music      = resample(df_Music,
                         replace=True,  
                         n_samples=2297, 
                         random_state=123)
df_War       = resample(df_War, 
                        replace=True,   
                        n_samples=2297,    
                        random_state=123)
df_Documentary= resample(df_Documentary, 
                         replace=True,
                         n_samples=2297,    
                         random_state=123)
df_Western    = resample(df_Western, 
                         replace=True,     
                         n_samples=2297,    
                         random_state=123)
df_Foreign   = resample(df_Foreign, 
                        replace=True,
                        n_samples=2297,  
                        random_state=123)
df_TV_Movie = resample(df_TV_Movie, 
                       replace=True, 
                       n_samples=2297,
                       random_state=123)

In [28]:
df_upsampled = pd.concat([df_Drama, df_Comedy], axis=0 ) 
df_upsampled = pd.concat([df_upsampled, df_Adventure], axis=0 )


df_upsampled = pd.concat([df_upsampled, df_Thriller ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Action ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Romance ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Crime ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Science_Fiction ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Horror ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Family ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Fantasy ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Mystery ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Animation ]
                         )
df_upsampled = pd.concat([df_upsampled, df_History ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Music ]
                         )
df_upsampled = pd.concat([df_upsampled, df_War ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Documentary ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Western ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Foreign ]
                         )
df_upsampled = pd.concat([df_upsampled, df_TV_Movie ]
                         )

In [29]:
df_upsampled.reset_index()

       index                                           overview    genres
0         12  Following the death of District Attorney Harve...     Drama
1         74  In 1933 New York, an overly ambitious movie pr...     Drama
2         76  84 years later, a 101-year-old woman named Ros...     Drama
3        139  Life for former United Nations investigator Ge...     Drama
4        153  An adaptation of F. Scott Fitzgerald's Long Is...     Drama
...      ...                                                ...       ...
45935  12158  "Signed, Sealed, Delivered" introduces a dedic...  TV Movie
45936   9934  Troy (Zac Efron), the popular captain of the b...  TV Movie
45937   8903  A young woman finds out that her mother worked...  TV Movie
45938  10413  The continued Westward journey of settlers Mis...  TV Movie
45939   9780  American-born Jayne Valseca, her husband Eduar...  TV Movie

[45940 rows x 3 columns]

In [30]:
df_upsampled['genres'].value_counts()

Animation          2297
Western            2297
Horror             2297
Documentary        2297
Mystery            2297
History            2297
Thriller           2297
Fantasy            2297
Drama              2297
Comedy             2297
Science Fiction    2297
Romance            2297
Foreign            2297
Action             2297
Crime              2297
TV Movie           2297
Adventure          2297
War                2297
Family             2297
Music              2297
Name: genres, dtype: int64

 # predicao com td-ifdf

In [31]:
df_upsampled['overview'].shape

(45940,)

In [32]:
df_upsampled['genres'].shape

(45940,)

In [33]:
from sklearn.preprocessing import MultiLabelBinarizer
multilabel_binarizer3 = MultiLabelBinarizer()
df_upsampled['genres'] = df_upsampled['genres'].map(lambda x: x.split(','))
y =multilabel_binarizer3.fit_transform( df_upsampled['genres'] )
tfidf_vectorizer3 = TfidfVectorizer(max_df=0.7, max_features=25000)
# from sklearn import model_selection
xtrain, xval, ytrain, yval = model_selection.train_test_split(df_upsampled['overview'].values, y, test_size=0.2, random_state=512)
xtrain_tfidf = tfidf_vectorizer3.fit_transform(xtrain)
xval_tfidf = tfidf_vectorizer3.transform(xval)
train_x = xtrain_tfidf
test_x = xval_tfidf

In [34]:
multilabel_binarizer3.classes_

array(['Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History',
       'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction',
       'TV Movie', 'Thriller', 'War', 'Western'], dtype=object)

In [35]:
from sklearn.naive_bayes import MultinomialNB 
parameters = {  
    "estimator__alpha": [1e-2, 1e-3,1e-4, 1e-5],
    
} 

 

# dict_keys(['C', 'class_weig:ht', 'dual', 'fit_intercept', 'intercept_scaling', 'l1_ratio', 'max_iter', 'multi_class', 'n_jobs', 'penalty', 'random_state', 'solver', 'tol', 'verbose', 'warm_start'])
rfc = OneVsRestClassifier(MultinomialNB( fit_prior=True, class_prior=None))
# grid_search_tune = GridSearchCV(
# rfc, parameters, cv=2, n_jobs=2, verbose=3)
# grid_search_tune.fit(train_x, ytrain )

In [36]:


classes=multilabel_binarizer3.classes_
print('_' * 120)


t0 = time()  
##############
print("Training: ")
grid_search_tune = GridSearchCV(
rfc, parameters, cv=2, n_jobs=2, verbose=4)
grid_search_tune.fit(train_x, ytrain )  

clf  = grid_search_tune.best_estimator_
print(clf)
print 
############################
train_time = time() - t0
print("Treino: %0.3fs" % train_time)

t0 = time()
pred = clf.predict(test_x)
test_time = time() - t0
print("testes:  %0.3fs" % test_time)

score = f1_score(yval, pred, average="micro")
precision = precision_score(yval, pred, average='micro')
print("accuracy:   %0.3f" % score)

print('\nAccuracy: {:.2f}\n'.format(accuracy_score(yval, pred)))

print('Micro Precision: {:.2f}'.format(precision_score(yval, pred, average='micro')))
print('Macro Precision: {:.2f}'.format(precision_score(yval, pred, average='macro')))
print('Weighted Precision: {:.2f}'.format(precision_score(yval, pred, average='weighted')))


print('Micro F1-score: {:.2f}\n'.format(f1_score(yval, pred, average='micro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(yval, pred, average='macro'))) 
print('Weighted F1-score: {:.2f}'.format(f1_score(yval, pred, average='weighted')))

print('Macro Recall: {:.2f}'.format(recall_score(yval, pred, average='macro'))) 
print('Micro Recall: {:.2f}'.format(recall_score(yval, pred, average='micro')))
print('Weighted Recall: {:.2f}'.format(recall_score(yval, pred, average='weighted')))

print("RelatÃ³rio de ClassificaÃ§Ã£o:")
print(classification_report(yval, pred,
#                                             labels=[1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
                                        target_names=classes))

# print("confusion matrix:") 
# print(confusion_matrix(yvalb2.argmax(axis=1), pred.argmax(axis=1)))


if hasattr(clf, 'coef_'):
    print("dimensionality: %d" % clf.coef_.shape[1])
#     print("density: %f" % density(clf.coef_))

clf_descr = 'LogisticRegression-semtratamento-td-ifdf-tmdb'#str(clf).split('(')[0]

test_time=55555    
results.append([clf_descr, score,precision, train_time, test_time])  
resultsLogisticRegression.append([clf_descr, score,precision, train_time, test_time])  
salvar_dado([clf_descr, score,precision, train_time, test_time])
# sklearn.metrics.mean_squared_errorÂ¶

________________________________________________________________________________________________________________________
Training:
Fitting 2 folds for each of 4 candidates, totalling 8 fits

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   8 out of   8 | elapsed:    4.7s remaining:    0.0s
[Parallel(n_jobs=2)]: Done   8 out of   8 | elapsed:    4.7s finished

OneVsRestClassifier(estimator=MultinomialNB(alpha=0.01))
Treino: 5.654s
testes:  0.161s
accuracy:   0.587

Accuracy: 0.38

Micro Precision: 0.50
Macro Precision: 0.51
Weighted Precision: 0.51
Micro F1-score: 0.59

Macro F1-score: 0.58

Weighted F1-score: 0.58
Macro Recall: 0.71
Micro Recall: 0.70
Weighted Recall: 0.70
RelatÃ³rio de ClassificaÃ§Ã£o:
                 precision    recall  f1-score   support

         Action       0.26      0.37      0.31       432
      Adventure       0.26      0.40      0.32       446
      Animation       0.52      0.95      0.67       446
         Comedy       0.34      0.33      0.33       471
          Crime       0.42      0.63      0.50       449
    Documentary       0.86      0.99      0.92       496
          Drama       0.03      0.02      0.02       466
         Family       0.36      0.66      0.47       483
        Fantasy       0.40      0.75      0.52       447
        Foreign       0.93      1.00      0.96       447
        History       0.54      0.95      0.69       424
         Horror       0.50      0.78      0.61       472
          Music       0.64      0.97      0.77       432
        Mystery       0.52      0.81      0.64       476
        Romance       0.48      0.55      0.51       503
Science Fiction       0.38      0.68      0.49       465
       TV Movie       0.98      1.00      0.99       472
       Thriller       0.24      0.30      0.27       463
            War       0.65      1.00      0.79       457
        Western       0.82      1.00      0.90       441

      micro avg       0.50      0.70      0.59      9188
      macro avg       0.51      0.71      0.58      9188
   weighted avg       0.51      0.70      0.58      9188
    samples avg       0.53      0.70      0.58      9188

dimensionality: 20685
<built-in function id>
['LogisticRegression-semtratamento-td-ifdf-tmdb', 0.5873123838026573, 0.5033812670034978, 5.653881311416626, 55555, '02/10/2020 11:29:38']
<built-in function id>

In [151]:
rfc.estimator.get_params().keys()

dict_keys(['C', 'class_weight', 'dual', 'fit_intercept', 'intercept_scaling', 'l1_ratio', 'max_iter', 'multi_class', 'n_jobs', 'penalty', 'random_state', 'solver', 'tol', 'verbose', 'warm_start'])

# MovieLens

In [37]:
movies = pd.read_csv('../../../dados/movielens/filmes_com_overview.csv')

In [38]:
# movies = movies['genres != (no genres listed)']:
movies = pd.read_csv('../../../dados/movielens/filmes_com_overview.csv')
movies.drop(movies[movies.genres == '(no genres listed)'].index, inplace=True)

In [39]:
movies['genres'].value_counts()

Drama                                                  8869
Comedy                                                 5422
Documentary                                            4573
Comedy|Drama                                           2338
Drama|Romance                                          2088
                                                       ...
Animation|Drama|Mystery                                   1
Adventure|Thriller|Western                                1
Children|Mystery|Sci-Fi                                   1
Adventure|Animation|Children|Comedy|Fantasy|Musical       1
Animation|Drama|Sci-Fi|IMAX                               1
Name: genres, Length: 1625, dtype: int64

In [40]:
(movies['genres'].values == '').sum()

0

In [41]:
movies['overview'].fillna('', inplace=True)
movies.isnull().sum()

movieId     0
title       0
genres      0
overview    0
dtype: int64

In [42]:
movies = movies[movies['genres'] != 'chi Fade to Black Kimi no Na o Yobu) (2008)']
movies = movies[movies['genres'] != ' Battle Force (1978)']
movies = movies[movies['genres'] != 'epe&#351']
movies = movies[movies['genres'] != '(no genres listed)']
movies = movies[movies['genres'] != 'Gate the Movie: The Burden of DÃ©jÃ  vu (2013)']
movies['genres'].value_counts()

Drama                                                        8869
Comedy                                                       5422
Documentary                                                  4573
Comedy|Drama                                                 2338
Drama|Romance                                                2088
                                                             ...
Action|Musical|Sci-Fi                                           1
Adventure|Animation|Comedy|Drama|Fantasy|Sci-Fi                 1
Adventure|Animation|Children|Comedy|Crime|Fantasy|Mystery       1
Animation|Children|Comedy|Musical|Sci-Fi                        1
Comedy|Drama|Film-Noir|Romance                                  1
Name: genres, Length: 1621, dtype: int64

In [43]:
generos = movies.genres.str.get_dummies()
generos.head()

,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [44]:
dados_dos_filmes = pd.concat([movies, generos], axis=1)
dados_dos_filmes.head()

,movieId,title,genres,overview,Action,Adventure,Animation,Children,Comedy,Crime,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Led by Woody, Andy's toys live happily in his ...",0,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),Adventure|Children|Fantasy,When siblings Judy and Peter discover an encha...,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),Comedy|Romance,A family wedding reignites the ancient feud be...,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,"Cheated on, mistreated and stepped on, the wom...",0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II (1995),Comedy,Just when George Banks has recovered from his ...,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [45]:
dados_dos_filmes = dados_dos_filmes[dados_dos_filmes['genres'] != 'chi Fade to Black Kimi no Na o Yobu) (2008)']
dados_dos_filmes = dados_dos_filmes[dados_dos_filmes['genres'] != ' Battle Force (1978)']
dados_dos_filmes = dados_dos_filmes[dados_dos_filmes['genres'] != 'epe&#351']
dados_dos_filmes = dados_dos_filmes[dados_dos_filmes['genres'] != '(no genres listed)']
dados_dos_filmes = dados_dos_filmes[dados_dos_filmes['genres'] != 'Gate the Movie: The Burden of DÃ©jÃ  vu (2013)']
dados_dos_filmes['genres'].value_counts()

Drama                                                        8869
Comedy                                                       5422
Documentary                                                  4573
Comedy|Drama                                                 2338
Drama|Romance                                                2088
                                                             ...
Action|Musical|Sci-Fi                                           1
Adventure|Animation|Comedy|Drama|Fantasy|Sci-Fi                 1
Adventure|Animation|Children|Comedy|Crime|Fantasy|Mystery       1
Animation|Children|Comedy|Musical|Sci-Fi                        1
Comedy|Drama|Film-Noir|Romance                                  1
Name: genres, Length: 1621, dtype: int64

In [46]:
df_genres

,Action,Adventure,Animation,Comedy,Crime,Documentary,Drama,Family,Fantasy,Foreign,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
4,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
4799,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4800,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
4801,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4802,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [47]:
dados_dos_filmes = dados_dos_filmes[dados_dos_filmes['genres'] != 'genres']
dados_dos_filmes = dados_dos_filmes[dados_dos_filmes['genres'] != 'Gate the Movie: The Burden of DÃ©jÃ  vu (2013)']
dados_dos_filmes.columns
df_genres.columns

Index(['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary',
       'Drama', 'Family', 'Fantasy', 'Foreign', 'History', 'Horror', 'Music',
       'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [48]:
categories

['Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Foreign',
 'History',
 'Horror',
 'Music',
 'Mystery',
 'Romance',
 'Science Fiction',
 'TV Movie',
 'Thriller',
 'War',
 'Western']

In [49]:

df_genres =dados_dos_filmes.drop(['movieId','title', 'overview'  ], axis=1)
counts = []
categories = list(df_genres.columns)
categories = categories[1:]
for i in categories:
    counts.append((i, df_genres[i].sum()))
df_stats = pd.DataFrame(counts, columns=['genre', '#movies'])
df_stats

          genre  #movies
0        Action     7242
1     Adventure     4054
2     Animation     2824
3      Children     2859
4        Comedy    16440
5         Crime     5215
6   Documentary     5410
7         Drama    25112
8       Fantasy     2644
9     Film-Noir      352
10       Horror     5935
11         IMAX      193
12      Musical     1039
13      Mystery     2863
14      Romance     7602
15       Sci-Fi     3528
16     Thriller     8569
17          War     1832
18      Western     1378

In [50]:
dados_dos_filmes.columns

Index(['movieId', 'title', 'genres', 'overview', 'Action', 'Adventure',
       'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'IMAX', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [73]:
# split the data, leave 1/3 out for testing
data_x = dados_dos_filmes[['overview']]
data_y = dados_dos_filmes.drop(['movieId', 'title', 'genres', 'overview'], axis=1)
# stratified_split = StratifiedShuffleSplit(n_splits=2, test_size=0.33)
xtrain, xval, ytrain, yval = model_selection.train_test_split(data_x, data_y, test_size=0.33, random_state=512)
# transform matrix of plots into lists to pass to a TfidfVectorizer
train_x =  [x[0].strip() for x in xtrain.values.tolist()]
test_x = [x[0].strip() for x in xval.values.tolist()]

In [75]:
len(test_x)

18506

In [76]:
len(yval )

18506

In [77]:
from sklearn.naive_bayes import MultinomialNB 
nltk.download('stopwords') 
words = stopwords.words("english") 
pipeline = Pipeline([
('tfidf', TfidfVectorizer(stop_words=words)),
('clf', OneVsRestClassifier(MultinomialNB( fit_prior=True, class_prior=None)) ),
    
])
from sklearn.naive_bayes import MultinomialNB 
parameters = {  
    "clf__estimator__alpha": [1e-2, 1e-3,1e-4, 1e-5],
    
}

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USUARIO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [80]:
grid_search_tune = GridSearchCV(
pipeline, parameters, cv=2, n_jobs=2, verbose=3)
grid_search_tune.fit(train_x, ytrain )  
print
print("Best parameters set:")
print (grid_search_tune.best_estimator_.steps)

Fitting 2 folds for each of 4 candidates, totalling 8 fits

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   8 out of   8 | elapsed:   14.5s remaining:    0.0s
[Parallel(n_jobs=2)]: Done   8 out of   8 | elapsed:   14.5s finished

Best parameters set:
[('tfidf', TfidfVectorizer(stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...])), ('clf', OneVsRestClassifier(estimator=MultinomialNB(alpha=0.01)))]

In [81]:


clf  = grid_search_tune.best_estimator_
classes=[ 'Action', 'Adventure',
       'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'IMAX', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
# print('_' * 120)
# print("Training: ")
# print(clf)
# t0 = time()  
# train_time = time() - t0
# print("Treino: %0.3fs" % train_time)

# t0 = time()
pred = clf.predict(test_x)
test_time = time() - t0
print("testes:  %0.3fs" % test_time)

score = f1_score(yval, pred, average="micro")
precision = precision_score(yval, pred, average='micro')
print("accuracy:   %0.3f" % score)

print('\nAccuracy: {:.2f}\n'.format(accuracy_score(yval, pred)))

print('Micro Precision: {:.2f}'.format(precision_score(yval, pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(yval, pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(yval, pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(yval, pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(yval, pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(yval, pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(yval, pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(yval, pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(yval, pred, average='weighted')))

print("RelatÃ³rio de ClassificaÃ§Ã£o:")
print(classification_report(yval, pred,
#                                             labels=[1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
                                        target_names=classes))

# print("confusion matrix:") 
# print(confusion_matrix(yvalb2.argmax(axis=1), pred.argmax(axis=1)))


if hasattr(clf, 'coef_'):
    print("dimensionality: %d" % clf.coef_.shape[1])
    print("density: %f" % density(clf.coef_))

clf_descr = 'movielens-grid-LogisticRegression-upsampled'#str(clf).split('(')[0]

test_time=55555    
results.append([clf_descr, score,precision, train_time, test_time])  
resultsLogisticRegression.append([clf_descr, score,precision, train_time, test_time])  
salvar_dado([clf_descr, score,precision, train_time, test_time])

testes:  663.930s
accuracy:   0.430

Accuracy: 0.20

Micro Precision: 0.68
Micro Recall: 0.32
Micro F1-score: 0.43

Macro Precision: 0.60
Macro Recall: 0.19
Macro F1-score: 0.27

Weighted Precision: 0.66
Weighted Recall: 0.32
Weighted F1-score: 0.40
RelatÃ³rio de ClassificaÃ§Ã£o:
              precision    recall  f1-score   support

      Action       0.67      0.26      0.37      2382
   Adventure       0.64      0.15      0.24      1283
   Animation       0.83      0.22      0.35       928
    Children       0.74      0.13      0.22       914
      Comedy       0.68      0.36      0.47      5452
       Crime       0.59      0.14      0.23      1643
 Documentary       0.80      0.41      0.54      1800
       Drama       0.66      0.59      0.63      8331
     Fantasy       0.63      0.09      0.16       857
   Film-Noir       0.00      0.00      0.00       113
      Horror       0.81      0.30      0.44      1909
        IMAX       0.00      0.00      0.00        65
     Musical       0.32      0.02      0.03       331
     Mystery       0.57      0.04      0.08       943
     Romance       0.54      0.09      0.16      2560
      Sci-Fi       0.80      0.27      0.41      1154
    Thriller       0.55      0.15      0.24      2828
         War       0.69      0.18      0.29       606
     Western       0.92      0.22      0.35       484

   micro avg       0.68      0.32      0.43     34583
   macro avg       0.60      0.19      0.27     34583
weighted avg       0.66      0.32      0.40     34583
 samples avg       0.48      0.37      0.39     34583

<built-in function id>
['movielens-grid-LogisticRegression-upsampled', 0.4304695816740922, 0.676330297961965, 5.653881311416626, 55555, '02/10/2020 11:29:38']
<built-in function id>

In [127]:
# movies['genres'].unique()

array(['Adventure|Animation|Children|Comedy|Fantasy',
       'Adventure|Children|Fantasy', 'Comedy|Romance', ...,
       'Comedy|Drama|Fantasy|War', 'Children|Comedy|Fantasy|Mystery',
       'Comedy|Horror|Mystery|Sci-Fi|Western'], dtype=object)

In [139]:
movies = pd.read_csv('../../../dados/movielens/filmes_com_overview.csv')
movies.drop(movies[movies.genres == '(no genres listed)'].index, inplace=True)

In [140]:
movies['genres'] = movies['genres'].fillna('[]')
movies['genres'] = movies['genres'].map(lambda x: x.split('|')) 
movies.head(3)

,movieId,title,genres,overview
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","Led by Woody, Andy's toys live happily in his ..."
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]",When siblings Judy and Peter discover an encha...
2,3,Grumpier Old Men (1995),"[Comedy, Romance]",A family wedding reignites the ancient feud be...

In [141]:
overview_df = movies[["overview","genres"]]
filmes_balanceados = overview_df.copy(deep=True)

In [142]:
filmes_balanceados.isnull().sum()

overview    0
genres      0
dtype: int64

In [143]:
lst_col = 'genres'

filmes_balanceados2 = pd.DataFrame({
      col:np.repeat(filmes_balanceados[col].values, filmes_balanceados[lst_col].str.len())
      for col in filmes_balanceados.columns.drop(lst_col)}
    ).assign(**{
    lst_col:np.concatenate(filmes_balanceados[lst_col].values)})[filmes_balanceados.columns]

In [144]:
df_Drama = filmes_balanceados2[filmes_balanceados2['genres']=='Drama']
df_Comedy  = filmes_balanceados2[filmes_balanceados2['genres']=='Comedy']
df_Thriller   = filmes_balanceados2[filmes_balanceados2['genres']=='Thriller']
df_Romance   = filmes_balanceados2[filmes_balanceados2['genres']=='Romance']
df_Action  = filmes_balanceados2[filmes_balanceados2['genres']=='Action']
df_Horror     = filmes_balanceados2[filmes_balanceados2['genres']=='Horror']
df_Documentary  = filmes_balanceados2[filmes_balanceados2['genres']=='Documentary']
df_Crime    = filmes_balanceados2[filmes_balanceados2['genres']=='Crime']
df_Adventure = filmes_balanceados2[filmes_balanceados2['genres']=='Adventure'] 
df_Mystery      = filmes_balanceados2[filmes_balanceados2['genres']=='Mystery'] 
df_Animation   = filmes_balanceados2[filmes_balanceados2['genres']=='Animation']
df_Fantasy    = filmes_balanceados2[filmes_balanceados2['genres']=='Fantasy'] 
df_War        = filmes_balanceados2[filmes_balanceados2['genres']=='War']
df_Western     = filmes_balanceados2[filmes_balanceados2['genres']=='Western']
df_Music         = filmes_balanceados2[filmes_balanceados2['genres']=='Musical']

df_Children           = filmes_balanceados2[filmes_balanceados2['genres']=='Children']
df_SciFi = filmes_balanceados2[filmes_balanceados2['genres']=='Sci-Fi']
df_FilmNoir           = filmes_balanceados2[filmes_balanceados2['genres']=='Film-Noir']
df_IMAX     = filmes_balanceados2[filmes_balanceados2['genres']=='IMAX']

In [145]:
df_Comedy  = resample(df_Comedy,
                      replace=True,
                      n_samples=25112,
                      random_state=0)
df_Thriller   = resample(df_Thriller,
                         replace=True,
                         n_samples=25112,
                         random_state=0)
df_Romance   = resample(df_Romance,
                        replace=True,
                        n_samples=25112,
                        random_state=0)
df_Action  = resample(df_Action,
                      replace=True,
                      n_samples=25112,
                      random_state=0)
df_Horror     = resample(df_Horror, 
                         replace=True,     
                         n_samples=25112,    
                         random_state=0)
df_Documentary= resample(df_Documentary, 
                         replace=True,
                         n_samples=25112,    
                         random_state=0)
df_Crime   = resample(df_Crime,
                      replace=True,     
                      n_samples=25112,    
                      random_state=0)
df_Adventure= resample(df_Adventure, 
                       replace=True,  
                       n_samples=25112,    
                       random_state=0)
df_Mystery      = resample(df_Mystery,
                           replace=True,     
                           n_samples=25112,   
                           random_state=0)
df_Animation  = resample(df_Animation, 
                         replace=True, 
                         n_samples=25112, 
                         random_state=0)
df_Fantasy   = resample(df_Fantasy, 
                                 replace=True,     
                                 n_samples=25112,    
                                 random_state=0) 

# df_Family          = resample(df_Family, 
#                               replace=True,
#                               n_samples=25112,  
#                               random_state=0)
df_War       = resample(df_War, 
                        replace=True,   
                        n_samples=25112,    
                        random_state=0)
df_Western    = resample(df_Western, 
                         replace=True,     
                         n_samples=25112,    
                         random_state=0)
df_Music      = resample(df_Music,
                         replace=True,  
                         n_samples=25112, 
                         random_state=0)  
df_Children    = resample(df_Children, 
                         replace=True, 
                         n_samples=25112,  
                         random_state=0) 
df_SciFi   = resample(df_SciFi, 
                        replace=True,
                        n_samples=25112,  
                        random_state=0)
df_FilmNoir   = resample(df_FilmNoir, 
                        replace=True,
                        n_samples=25112,  
                        random_state=0)


df_IMAX = resample(df_IMAX, 
                       replace=True, 
                       n_samples=25112,
                       random_state=0)

In [146]:
df_upsampled = pd.concat([df_Drama, df_Comedy], axis=0 )
df_upsampled = pd.concat([df_upsampled, df_Thriller ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Action ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Adventure ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Romance ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Crime ]
                         )
df_upsampled = pd.concat([df_upsampled, df_SciFi ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Horror ]
                         ) 
df_upsampled = pd.concat([df_upsampled, df_Fantasy ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Mystery ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Animation ]
                         )  
df_upsampled = pd.concat([df_upsampled, df_Music ]
                         )
df_upsampled = pd.concat([df_upsampled, df_War ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Documentary ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Western ]
                         )  
df_upsampled = pd.concat([df_upsampled, df_Children ]
                         )
df_upsampled = pd.concat([df_upsampled, df_FilmNoir ]
                         )
df_upsampled = pd.concat([df_upsampled, df_IMAX ]
                         )

In [147]:
df_upsampled.reset_index()

        index                                           overview genres
0          11  Cheated on, mistreated and stepped on, the wom...  Drama
1          26  Widowed U.S. president Andrew Shepherd, one of...  Drama
2          33  A look at President Richard M. Nixonâ€”a man car...  Drama
3          38  In early-1970s Las Vegas, low-level mobster Sa...  Drama
4          39  Rich Mr. Dashwood dies, leaving his second wif...  Drama
...       ...                                                ...    ...
477123  21176  Harry starts his fourth year at Hogwarts, comp...   IMAX
477124  41826  Jack Ryan, as a young covert CIA analyst, unco...   IMAX
477125  41996  200 years after his shocking creation, Dr. Fra...   IMAX
477126  39987  In 1942, Henan Province was devastated by the ...   IMAX
477127  38786  After getting a taste for blood as children, H...   IMAX

[477128 rows x 3 columns]

In [148]:
df_upsampled['genres'].value_counts()

Children       25112
Sci-Fi         25112
Action         25112
Crime          25112
Film-Noir      25112
Mystery        25112
Thriller       25112
Fantasy        25112
Animation      25112
War            25112
Musical        25112
Drama          25112
IMAX           25112
Romance        25112
Horror         25112
Comedy         25112
Western        25112
Adventure      25112
Documentary    25112
Name: genres, dtype: int64

# Refazer prediÃ§Ã£o com resample

In [88]:
# split the data, leave 1/3 out for testing
data_x = dados_dos_filmes[['overview']]
data_y = dados_dos_filmes.drop(['movieId', 'title', 'genres', 'overview'], axis=1)
# stratified_split = StratifiedShuffleSplit(n_splits=2, test_size=0.33)
xtrain, xval, ytrain, yval = model_selection.train_test_split(data_x, data_y, test_size=0.33, random_state=512)
# transform matrix of plots into lists to pass to a TfidfVectorizer
train_x = [x[0].strip() for x in xtrain.values.tolist()]
test_x = [x[0].strip() for x in xval.values.tolist()]

In [89]:
  
from sklearn.naive_bayes import MultinomialNB 
nltk.download('stopwords') 
words = stopwords.words("english") 
pipeline = Pipeline([
('tfidf', TfidfVectorizer(stop_words=words)),
('clf', OneVsRestClassifier(MultinomialNB( fit_prior=True, class_prior=None)) ),
    
])
from sklearn.naive_bayes import MultinomialNB 
parameters = {  
    "clf__estimator__alpha": [1e-2, 1e-3,1e-4, 1e-5],
    
}

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USUARIO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [90]:

grid_search_tune = GridSearchCV(
pipeline, parameters, cv=2, n_jobs=2, verbose=3)
grid_search_tune.fit(train_x, ytrain )  
print
print("Best parameters set:")
print (grid_search_tune.best_estimator_.steps)

Fitting 2 folds for each of 4 candidates, totalling 8 fits

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   8 out of   8 | elapsed:   14.8s remaining:    0.0s
[Parallel(n_jobs=2)]: Done   8 out of   8 | elapsed:   14.8s finished

Best parameters set:
[('tfidf', TfidfVectorizer(stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...])), ('clf', OneVsRestClassifier(estimator=MultinomialNB(alpha=0.01)))]

In [91]:

clf  = grid_search_tune.best_estimator_
classes=[ 'Action', 'Adventure',
       'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'IMAX', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
print('_' * 120)
print("Training: ")
print(clf)
t0 = time()  
train_time = time() - t0
print("Treino: %0.3fs" % train_time)

t0 = time()
pred = clf.predict(test_x)
test_time = time() - t0
print("testes:  %0.3fs" % test_time)

score = f1_score(yval, pred, average="micro")
precision = precision_score(yval, pred, average='micro')
print("accuracy:   %0.3f" % score)

print('\nAccuracy: {:.2f}\n'.format(accuracy_score(yval, pred)))

print('Micro Precision: {:.2f}'.format(precision_score(yval, pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(yval, pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(yval, pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(yval, pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(yval, pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(yval, pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(yval, pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(yval, pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(yval, pred, average='weighted')))

print("RelatÃ³rio de ClassificaÃ§Ã£o:")
print(classification_report(yval, pred,
#                                             labels=[1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
                                        target_names=classes))

# print("confusion matrix:") 
# print(confusion_matrix(yvalb2.argmax(axis=1), pred.argmax(axis=1)))


if hasattr(clf, 'coef_'):
    print("dimensionality: %d" % clf.coef_.shape[1])
    print("density: %f" % density(clf.coef_))

clf_descr = 'LogisticRegression-upsampled'#str(clf).split('(')[0]

test_time=55555    
results.append([clf_descr, score,precision, train_time, test_time])  
resultsLogisticRegression.append([clf_descr, score,precision, train_time, test_time])  
salvar_dado([clf_descr, score,precision, train_time, test_time])

________________________________________________________________________________________________________________________
Training:
Pipeline(steps=[('tfidf',
                 TfidfVectorizer(stop_words=['i', 'me', 'my', 'myself', 'we',
                                             'our', 'ours', 'ourselves', 'you',
                                             "you're", "you've", "you'll",
                                             "you'd", 'your', 'yours',
                                             'yourself', 'yourselves', 'he',
                                             'him', 'his', 'himself', 'she',
                                             "she's", 'her', 'hers', 'herself',
                                             'it', "it's", 'its', 'itself', ...])),
                ('clf',
                 OneVsRestClassifier(estimator=MultinomialNB(alpha=0.01)))])
Treino: 0.001s
testes:  1.240s
accuracy:   0.430

Accuracy: 0.20

Micro Precision: 0.68
Micro Recall: 0.32
Micro F1-score: 0.43

Macro Precision: 0.60
Macro Recall: 0.19
Macro F1-score: 0.27

Weighted Precision: 0.66
Weighted Recall: 0.32
Weighted F1-score: 0.40
RelatÃ³rio de ClassificaÃ§Ã£o:
              precision    recall  f1-score   support

      Action       0.67      0.26      0.37      2382
   Adventure       0.64      0.15      0.24      1283
   Animation       0.83      0.22      0.35       928
    Children       0.74      0.13      0.22       914
      Comedy       0.68      0.36      0.47      5452
       Crime       0.59      0.14      0.23      1643
 Documentary       0.80      0.41      0.54      1800
       Drama       0.66      0.59      0.63      8331
     Fantasy       0.63      0.09      0.16       857
   Film-Noir       0.00      0.00      0.00       113
      Horror       0.81      0.30      0.44      1909
        IMAX       0.00      0.00      0.00        65
     Musical       0.32      0.02      0.03       331
     Mystery       0.57      0.04      0.08       943
     Romance       0.54      0.09      0.16      2560
      Sci-Fi       0.80      0.27      0.41      1154
    Thriller       0.55      0.15      0.24      2828
         War       0.69      0.18      0.29       606
     Western       0.92      0.22      0.35       484

   micro avg       0.68      0.32      0.43     34583
   macro avg       0.60      0.19      0.27     34583
weighted avg       0.66      0.32      0.40     34583
 samples avg       0.48      0.37      0.39     34583

<built-in function id>
['LogisticRegression-upsampled', 0.4304695816740922, 0.676330297961965, 0.0009975433349609375, 55555, '02/10/2020 11:29:38']
<built-in function id>

# Refazer prediÃ§Ã£o com resample e IF-IDF

In [92]:
df_upsampled = pd.concat([df_Drama, df_Comedy], axis=0 )
df_upsampled = pd.concat([df_upsampled, df_Thriller ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Action ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Adventure ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Romance ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Crime ]
                         )
df_upsampled = pd.concat([df_upsampled, df_SciFi ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Horror ]
                         ) 
df_upsampled = pd.concat([df_upsampled, df_Fantasy ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Mystery ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Animation ]
                         )  
df_upsampled = pd.concat([df_upsampled, df_Music ]
                         )
df_upsampled = pd.concat([df_upsampled, df_War ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Documentary ]
                         )
df_upsampled = pd.concat([df_upsampled, df_Western ]
                         )  
df_upsampled = pd.concat([df_upsampled, df_Children ]
                         )
df_upsampled = pd.concat([df_upsampled, df_FilmNoir ]
                         )
df_upsampled = pd.concat([df_upsampled, df_IMAX ]
                         )

In [93]:
df_upsampled.reset_index()

        index                                           overview   genres
0          12  Following the death of District Attorney Harve...    Drama
1          74  In 1933 New York, an overly ambitious movie pr...    Drama
2          76  84 years later, a 101-year-old woman named Ros...    Drama
3         139  Life for former United Nations investigator Ge...    Drama
4         153  An adaptation of F. Scott Fitzgerald's Long Is...    Drama
...       ...                                                ...      ...
328748  10873  In 1870s Texas, a ruthless bounty hunter and a...  Western
328749  10151  Double-crossed and left without water in the d...  Western
328750  10873  In 1870s Texas, a ruthless bounty hunter and a...  Western
328751  10258  A senator, who became famous for killing a not...  Western
328752   5193  Four unwitting heroes cross paths on their jou...  Western

[328753 rows x 3 columns]

(328753,)

In [94]:
df_upsampled['genres'] = df_upsampled['genres'].map(lambda x: x.split(','))
df_upsampled['genres'].head()

12     [Drama]
74     [Drama]
76     [Drama]
139    [Drama]
153    [Drama]
Name: genres, dtype: object

In [95]:
multilabel_binarizer3 = MultiLabelBinarizer()
y =multilabel_binarizer3.fit_transform(df_upsampled['genres'])

In [96]:
multilabel_binarizer3.classes_

array(['Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Horror', 'Mystery', 'Romance',
       'Thriller', 'War', 'Western'], dtype=object)

In [97]:
from sklearn.preprocessing import MultiLabelBinarizer
multilabel_binarizer3 = MultiLabelBinarizer()
y =multilabel_binarizer3.fit_transform(df_upsampled['genres'])
tfidf_vectorizer3 = TfidfVectorizer(max_df=0.7, max_features=5000)
# from sklearn import model_selection
xtrain, xval, ytrain, yval = model_selection.train_test_split(df_upsampled['overview'], y, test_size=0.2, random_state=512)
xtrain_tfidf = tfidf_vectorizer3.fit_transform(xtrain)
xval_tfidf = tfidf_vectorizer3.transform(xval)
train_x = xtrain_tfidf
test_x = xval_tfidf

In [104]:
 
from sklearn.naive_bayes import MultinomialNB 
parameters = {  
    "estimator__alpha": [1e-2, 1e-3,1e-4, 1e-5],
}
rfc = OneVsRestClassifier(MultinomialNB( fit_prior=True, class_prior=None))
# grid_search_tune = GridSearchCV(
# rfc, parameters, cv=2, n_jobs=2, verbose=3)
# grid_search_tune.fit(train_x, ytrain )

In [106]:


classes=multilabel_binarizer3.classes_
print('_' * 120)


t0 = time()  
##############
print("Training: ")
grid_search_tune = GridSearchCV(
rfc, parameters, cv=2, n_jobs=2, verbose=3)
grid_search_tune.fit(train_x, ytrain )  

clf  = grid_search_tune.best_estimator_
print(clf)
print 
############################
train_time = time() - t0
print("Treino: %0.3fs" % train_time)

t0 = time()
pred = clf.predict(test_x)
test_time = time() - t0
print("testes:  %0.3fs" % test_time)

score = f1_score(yval, pred, average="micro")
precision = precision_score(yval, pred, average='micro')
print("accuracy:   %0.3f" % score)

print('\nAccuracy: {:.2f}\n'.format(accuracy_score(yval, pred)))

print('Micro Precision: {:.2f}'.format(precision_score(yval, pred, average='micro')))
print('Macro Precision: {:.2f}'.format(precision_score(yval, pred, average='macro')))
print('Weighted Precision: {:.2f}'.format(precision_score(yval, pred, average='weighted')))


print('Micro F1-score: {:.2f}\n'.format(f1_score(yval, pred, average='micro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(yval, pred, average='macro'))) 
print('Weighted F1-score: {:.2f}'.format(f1_score(yval, pred, average='weighted')))

print('Macro Recall: {:.2f}'.format(recall_score(yval, pred, average='macro'))) 
print('Micro Recall: {:.2f}'.format(recall_score(yval, pred, average='micro')))
print('Weighted Recall: {:.2f}'.format(recall_score(yval, pred, average='weighted')))

print("RelatÃ³rio de ClassificaÃ§Ã£o:")
print(classification_report(yval, pred,
#                                             labels=[1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
                                        target_names=classes))

# print("confusion matrix:") 
# print(confusion_matrix(yvalb2.argmax(axis=1), pred.argmax(axis=1)))


# if hasattr(clf, 'coef_'):
#     print("dimensionality: %d" % clf.coef_.shape[1])
#     print("density: %f" % density(clf.coef_))

clf_descr = 'LogisticRegression-upsampled'#str(clf).split('(')[0]

test_time=55555    
results.append([clf_descr, score,precision, train_time, test_time])  
resultsLogisticRegression.append([clf_descr, score,precision, train_time, test_time])  
salvar_dado([clf_descr, score,precision, train_time, test_time])

________________________________________________________________________________________________________________________
Training:
Fitting 2 folds for each of 4 candidates, totalling 8 fits

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   8 out of   8 | elapsed:   12.6s remaining:    0.0s
[Parallel(n_jobs=2)]: Done   8 out of   8 | elapsed:   12.6s finished

OneVsRestClassifier(estimator=MultinomialNB(alpha=0.001))
Treino: 15.716s
testes:  0.637s
accuracy:   0.542

Accuracy: 0.39

Micro Precision: 0.70
Macro Precision: 0.55
Weighted Precision: 0.58
Micro F1-score: 0.54

Macro F1-score: 0.43

Weighted F1-score: 0.46
Macro Recall: 0.41
Micro Recall: 0.44
Weighted Recall: 0.44
RelatÃ³rio de ClassificaÃ§Ã£o:
              precision    recall  f1-score   support

      Action       0.31      0.04      0.07      5092
   Adventure       0.38      0.08      0.13      5078
   Animation       0.72      0.84      0.77      5096
      Comedy       0.46      0.04      0.08      5096
       Crime       0.49      0.23      0.32      5034
 Documentary       0.98      0.98      0.98      4998
       Drama       0.00      0.00      0.00       424
     Fantasy       0.50      0.40      0.44      5033
      Horror       0.57      0.44      0.50      5045
     Mystery       0.58      0.49      0.53      4914
     Romance       0.66      0.28      0.39      4910
    Thriller       0.31      0.01      0.03      5056
         War       0.83      0.96      0.89      5000
     Western       0.88      1.00      0.93      4975

   micro avg       0.70      0.44      0.54     65751
   macro avg       0.55      0.41      0.43     65751
weighted avg       0.58      0.44      0.46     65751
 samples avg       0.42      0.44      0.42     65751

<built-in function id>
['LogisticRegression-upsampled', 0.5418983449990188, 0.7027485578554462, 15.716230630874634, 55555, '02/10/2020 11:29:38']
<built-in function id>